name: 'Xwalk Boilerplate Handler'
description: 'Detects boilerplate packages and optionally converts them to use repository-specific paths'
inputs:
  zip_contents_path:
    description: 'Path to the extracted import zip contents'
    required: true
  page_paths:
    description: 'Comma-separated list of page paths from filter.xml (optional for detection)'
    required: false
  repo_name:
    description: 'Repository name to use for path replacement (required only for conversion)'
    required: false
  convert:
    description: 'Whether to convert boilerplate content (true/false). If false, only detection is performed.'
    required: false
    default: 'false'
outputs:
  is_boilerplate:
    description: 'Whether the package is a boilerplate'
  content_package_path:
    description: 'Path to the content package zip file'
  page_paths:
    description: 'Comma-separated list of page paths from filter.xml'
  converted_package_path:
    description: 'Path to the converted content package (if conversion was performed)'
  converted_page_paths:
    description: 'JSON string of converted page paths (if conversion was performed)'
  error_message:
    description: 'Error message if the operation failed'
runs:
  using: 'node20'
  main: 'xwalk.js'
