name: 'STA Boilerplate Detector'
description: 'Quickly detects if a package is a boilerplate by checking filter.xml paths'
inputs:
  zip_contents_path:
    description: 'Path to the extracted import zip contents'
    required: true
outputs:
  is_boilerplate:
    description: 'Whether the package is a boilerplate'
  content_package_path:
    description: 'Path to the content package zip file'
  page_paths:
    description: 'Comma-separated list of page paths from filter.xml'
  error_message:
    description: 'Error message if the operation failed'
runs:
  using: 'node20'
  main: 'sta-boilerplate-detector.js'
